### ISSUE TITLE
Я выполнила задание.

### ISSUE THREAD

**Issue by kulawina** [MIEE-ACS/domashnee-zadanie-no5-kulawina#1]
Мой вариант №16.
Проверьте ,  пожалуйста.

**Comment by d-makarenko** [comment]
Метод ToString написан неправильно
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/how-to-override-the-tostring-method

**Comment by kulawina** [comment]
Вот он 
public void ToString()
            {
                Console.WriteLine("{0}/{1}", numerator, denominator);
            }

**Comment by d-makarenko** [comment]
А я и не говорил что его нет. Он неправильный, прочитай текст по ссылке.

**Comment by d-makarenko** [comment]
В целом хорошо, но проблемы с ToString еще остались
4/4
